[http.routers]
  [http.routers.phoenix]
    rule = "Host(`localhost`)"
    service = "phoenix"
    entrypoints = ["web"]
    middlewares = []

[http.services]
  [http.services.phoenix.loadBalancer]
    [[http.services.phoenix.loadBalancer.servers]]
      url = "http://127.0.0.1:4000"
