---

- include_tasks: basics.yml
  when: action == "basics"

- include_tasks: cloud-sql.yml
  when: action == "cloud-sql"

- include_tasks: packages.yml
  when: action == "packages"

- include_tasks: postgis.yml
  when: action == "postgis"

- include_tasks: user.yml
  when: action == "user"
