---
- name: Basic Ansible Setup for SteinExample
  gather_facts: yes
  hosts: all
  collections:
    - devsec.hardening
  roles:
    - { role: ssh_hardening, become: yes, tags: ["ssh"] }
    - { role: firewall, become: yes, tags: ["setup", "firewall"] }
    - { role: jnv.unattended-upgrades, become: yes, tags: ["upgrades"] }
    - { role: geerlingguy.ntp, become: yes, tags: ["ntp"] }
    - { role: setup, action: "basics", tags: ["user"] }
    - { role: smartlogic.github_keys, tags: ["user"] }
    - { role: traefik, tags: ["web"] }

- name: Install postgres
  gather_facts: yes
  hosts:
    - local
  roles:
    - { role: geerlingguy.postgresql, become: yes, tags: ["postgres"] }
